from rest_framework import serializers
from core import models
class AppointmentSerializer(serializers.ModelSerializer):
    class Meta:
        model = models.Appointment
        fields = ['id', 'freelancer', 'category', 'skills_passed', 'done','appointment_date','appointment_date_options']
        read_only_fields = ['id' ,'skills_passed' , 'done']  # ID is read-only as it is autogenerated

class FreelancerInterviewSerializer(serializers.ModelSerializer):
    class Meta:
        model = models.FreelancerInterview
        fields = ['id', 'interviewer', 'freelancer', 'appointment', 'passed', 'feedback','done']
        read_only_fields = ['id']  # ID is read-only as it is autogenerated

class InterviewerSerializer(serializers.ModelSerializer):
    class Meta:
        model = models.Interviewer
        fields = [
            'id',
            'full_name',          
            'expertise',          
            'phone_number',      
            'interviews_per_week' 
        ]
        read_only_fields = ['id']  # ID is read-only as it is autogenerated

class AppointmentDateSelectionSerializer(serializers.Serializer):
    """Serializer for selecting an appointment date"""
    selected_date = serializers.CharField()

    def validate_selected_date(self, value):
        """Ensure that the selected date is a valid option"""
        # Get the current appointment instance (passed from the view)
        appointment = self.context['appointment']

        # Validate that the selected date is one of the available options
        date_options = appointment.appointment_date_options

        if value not in [option['date'] for option in date_options]:
            raise serializers.ValidationError("Selected date is not a valid option.")
        
        return value
