# Generated by Django 5.0.6 on 2024-07-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_pictures/')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('professional_title', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('portfolio', models.JSONField(blank=True, default=list)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('availability_status', models.CharField(default='Available', max_length=20)),
                ('preferred_working_hours', models.CharField(blank=True, max_length=100)),
                ('preferred_communication_channels', models.JSONField(blank=True, default=list)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('reviews', models.JSONField(blank=True, default=list)),
                ('user_role', models.CharField(default='Freelancer', max_length=20)),
                ('account_status', models.CharField(default='Active', max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('languages_spoken', models.JSONField(blank=True, default=list)),
                ('payment_methods', models.JSONField(blank=True, default=list)),
                ('payment_details', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
