# Generated by Django 5.0.6 on 2024-08-06 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 13, 13, 16, 3, 266795, tzinfo=datetime.timezone.utc)),
        ),
    ]
