# Generated by Django 5.0.6 on 2024-07-13 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='user',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='languages_spoken',
        ),
        migrations.RemoveField(
            model_name='user',
            name='professional_title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_communication_channels',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_working_hours',
        ),
        migrations.RemoveField(
            model_name='user',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_links',
        ),
        migrations.RemoveField(
            model_name='user',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=50, unique=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='payment_details',
        ),
        migrations.RemoveField(
            model_name='user',
            name='payment_methods',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_role',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('projects_posted', models.PositiveIntegerField(default=0)),
                ('average_project_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_freelancers', models.JSONField(blank=True, default=list)),
                ('verified', models.BooleanField(blank=True, default=False)),
                ('reviews', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('professional_title', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('portfolio', models.JSONField(blank=True, default=list)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('availability_status', models.CharField(default='Available', max_length=20)),
                ('preferred_working_hours', models.CharField(blank=True, max_length=100)),
                ('preferred_communication_channels', models.JSONField(blank=True, default=list)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('reviews', models.JSONField(blank=True, default=list)),
                ('languages_spoken', models.JSONField(blank=True, default=list)),
                ('verified', models.BooleanField(blank=True, default=False)),
                ('selected_payment_method', models.ManyToManyField(blank=True, to='core.paymentmethod')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
    ]
