# Generated by Django 5.0.6 on 2024-07-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_reviews_remove_user_certifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact_person',
        ),
    ]
