# Generated by Django 5.0.6 on 2024-08-07 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_technology_alter_dispute_response_deadline_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 13, 34, 30, 778796, tzinfo=datetime.timezone.utc)),
        ),
    ]
