# Generated by Django 5.0.6 on 2024-08-07 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_resume_password_alter_dispute_response_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 13, 34, 48, 464414, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='resume',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
