# Generated by Django 5.0.6 on 2024-08-07 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_dispute_response_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='average_project_budget',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='preferred_communication_channels',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='social_links',
        ),
        migrations.AddField(
            model_name='client',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='prev_work_experience',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='projects_posted',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='reviews',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 14, 16, 7, 26, 241787, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='certifications',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='languages_spoken',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='portfolio',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='preferred_working_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='reviews',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='selected_payment_method',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
