# Generated by Django 5.0.6 on 2024-08-18 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_client_average_project_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 12, 21, 34, 525337, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='preferred_working_hours',
            field=models.CharField(blank=True, choices=[('full_time', 'Full time (40 or more hrs/week)'), ('part_time', 'Part time (Less than 40 hrs/week)'), ('hourly', 'Hourly')], max_length=20, null=True),
        ),
    ]
