# Generated by Django 5.0.6 on 2024-07-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_project_budget_alter_project_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='selected_payment_method',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='selected_payment_method',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
