# Generated by Django 5.0.6 on 2024-08-18 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_service_created_at_remove_service_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 12, 24, 58, 470397, tzinfo=datetime.timezone.utc)),
        ),
    ]
