# Generated by Django 5.0.6 on 2024-08-18 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_dispute_response_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 12, 30, 42, 99251, tzinfo=datetime.timezone.utc)),
        ),
    ]
