# Generated by Django 5.0.6 on 2024-07-17 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='client_signed',
            new_name='freelancer_accepted_terms',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='freelancer_signed',
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='core.client'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='freelancer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='core.freelancer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('fully_paid', 'Fully Paid'), ('partially_paid', 'Partially Paid'), ('failed', 'Failed')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='core.project'),
        ),
    ]
