# Generated by Django 5.0.6 on 2024-07-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_client_signed_contract_freelancer_accepted_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount_agreed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
