# Generated by Django 5.0.6 on 2024-08-18 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_dispute_response_deadline'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 13, 19, 25, 184930, tzinfo=datetime.timezone.utc)),
        ),
    ]
