# Generated by Django 5.0.6 on 2024-07-18 12:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dispute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispute',
            name='created_by',
        ),
        migrations.AddField(
            model_name='dispute',
            name='auto_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 12, 52, 33, 55287, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contract'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.freelancer'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='return_type',
            field=models.CharField(choices=[('full', 'Full Refund'), ('partial', 'Partial Refund')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('auto_resolved', 'Auto Resolved')], default='open', max_length=20),
        ),
        migrations.RemoveField(
            model_name='dispute',
            name='supporting_documents',
        ),
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dispute_docs/')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dispute',
            name='supporting_documents',
            field=models.ManyToManyField(blank=True, to='core.supportingdocument'),
        ),
    ]
