# Generated by Django 5.0.6 on 2024-07-18 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_dispute_created_by_dispute_auto_resolved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 13, 2, 17, 797395, tzinfo=datetime.timezone.utc)),
        ),
    ]
