# Generated by Django 5.0.6 on 2024-07-18 13:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_dispute_response_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_disputes', to='core.client'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contract'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='freelancer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancer_disputes', to='core.freelancer'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 13, 27, 0, 406836, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='supportingdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
