# Generated by Django 5.0.6 on 2024-07-18 14:18

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_dispute_created_by_alter_dispute_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdocument',
            name='dispute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dispute'),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 25, 14, 18, 7, 469119, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='supporting_documents',
            field=models.ManyToManyField(blank=True, related_name='related_disputes', to='core.supportingdocument'),
        ),
    ]
