# Generated by Django 5.0.6 on 2024-08-25 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_message_read_alter_dispute_response_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, unique=True)),
                ('search_count', models.PositiveIntegerField(default=0)),
                ('last_searched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 11, 2, 49, 542064, tzinfo=datetime.timezone.utc)),
        ),
    ]
