# Generated by Django 5.0.6 on 2024-08-25 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_skillsearch_alter_dispute_response_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='selected_payment_method',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 1, 14, 3, 48, 415155, tzinfo=datetime.timezone.utc)),
        ),
    ]
