# Generated by Django 5.0.6 on 2024-09-15 16:03

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_client_selected_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=100)),
                ('expertise', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('interviews_per_week', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.user',),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 16, 3, 22, 514637, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('skills_passed', models.JSONField(default=list)),
                ('appointment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('freelancer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.freelancer')),
            ],
            options={
                'ordering': ['appointment_date'],
            },
        ),
    ]
