# Generated by Django 5.0.6 on 2024-07-23 09:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_dispute_response_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='payment_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('paid', 'Paid'), ('failed', 'Failed')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('paid', 'Paid'), ('failed', 'Failed')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 9, 46, 35, 953297, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_deposited', models.BooleanField(blank=True, default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Released', 'Released')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contract')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.milestone')),
            ],
        ),
    ]
