# Generated by Django 5.0.6 on 2024-09-15 16:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_interviewer_alter_dispute_response_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 16, 5, 18, 320020, tzinfo=datetime.timezone.utc)),
        ),
    ]
