# Generated by Django 5.0.6 on 2024-07-23 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_milestone_payment_status_milestone_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='deposit_confirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 13, 28, 6, 375077, tzinfo=datetime.timezone.utc)),
        ),
    ]
