# Generated by Django 5.0.6 on 2024-09-15 16:07

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_dispute_response_deadline_interview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 16, 7, 23, 546784, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='FreelancerInterview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passed', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appointment')),
                ('freelancer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancer_interviews', to='core.freelancer')),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviewer_interviews', to='core.interviewer')),
            ],
        ),
    ]
