# Generated by Django 5.0.6 on 2024-09-21 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_dispute_response_deadline_freelancerinterview'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_date_options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='appointment',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 28, 14, 27, 39, 102027, tzinfo=datetime.timezone.utc)),
        ),
    ]
