# Generated by Django 5.0.6 on 2024-07-23 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_escrow_deposit_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 13, 43, 8, 355583, tzinfo=datetime.timezone.utc)),
        ),
    ]
