# Generated by Django 5.0.6 on 2024-07-23 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_amount_deposited_escrow_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 13, 55, 28, 726982, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='escrow',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
