# Generated by Django 5.0.6 on 2024-07-23 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_dispute_response_deadline_alter_escrow_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escrow',
            name='amount_deposited',
        ),
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 15, 47, 22, 44724, tzinfo=datetime.timezone.utc)),
        ),
    ]
