# Generated by Django 5.0.6 on 2024-09-22 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_dispute_response_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 29, 13, 7, 5, 319249, tzinfo=datetime.timezone.utc)),
        ),
    ]
