# Generated by Django 5.0.6 on 2024-07-23 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_escrow_amount_deposited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 15, 47, 48, 778820, tzinfo=datetime.timezone.utc)),
        ),
    ]
