# Generated by Django 5.0.6 on 2024-07-24 10:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_dispute_response_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 10, 54, 25, 460054, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='escrow',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.milestone', unique=True),
        ),
    ]
