# Generated by Django 5.0.6 on 2024-09-22 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_dispute_response_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 29, 14, 20, 42, 670052, tzinfo=datetime.timezone.utc)),
        ),
    ]
