# Generated by Django 5.0.6 on 2024-09-22 15:26

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_notification_data_alter_dispute_response_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerinterview',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewer',
            name='working_hours_end',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='interviewer',
            name='working_hours_start',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 29, 15, 25, 58, 858874, tzinfo=datetime.timezone.utc)),
        ),
    ]
