# Generated by Django 5.0.6 on 2024-09-22 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_freelancerinterview_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewer',
            name='max_interviews_per_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 29, 15, 37, 32, 281773, tzinfo=datetime.timezone.utc)),
        ),
    ]
