# Generated by Django 5.0.6 on 2024-09-28 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_message_file_alter_dispute_response_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 11, 41, 50, 561413, tzinfo=datetime.timezone.utc)),
        ),
    ]
