# Generated by Django 5.0.6 on 2024-09-28 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_contract_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 14, 31, 22, 390813, tzinfo=datetime.timezone.utc)),
        ),
    ]
