# Generated by Django 5.0.6 on 2024-09-28 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_dispute_response_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 14, 34, 43, 86487, tzinfo=datetime.timezone.utc)),
        ),
    ]
