# Generated by Django 5.0.6 on 2024-09-28 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_dispute_response_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 14, 50, 22, 233091, tzinfo=datetime.timezone.utc)),
        ),
    ]
