# Generated by Django 5.0.6 on 2024-09-29 02:18

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_contract_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='milestone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.milestone'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='response_deadline',
            field=models.DateTimeField(default=core.models.default_deadline),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='return_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
