# Generated by Django 5.0.6 on 2024-09-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_dispute_milestone_alter_dispute_response_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('inDsipute', 'InDispute'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
