# Generated by Django 5.0.6 on 2024-10-01 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_counteroffer_counteroffermilestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counteroffermilestone',
            name='is_completed',
        ),
    ]
