# Generated by Django 5.0.6 on 2024-10-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_counteroffermilestone_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='counteroffer',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counteroffer',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
