# Generated by Django 5.0.6 on 2024-10-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_counteroffer_end_date_counteroffer_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='counteroffer',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
