# Generated by Django 5.0.6 on 2024-10-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_counteroffer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('accepted', 'accepted'), ('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('inDispute', 'InDispute')], default='draft', max_length=20),
        ),
    ]
