# Generated by Django 5.0.6 on 2024-10-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counteroffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
