# Generated by Django 5.0.6 on 2024-10-27 13:54

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_counteroffer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispute',
            name='auto_resolved',
        ),
        migrations.AddField(
            model_name='dispute',
            name='got_response',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DisputeResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('auto_resolved', 'Auto Resolved')], default='open', max_length=20)),
                ('return_type', models.CharField(choices=[('full', 'Full Refund'), ('partial', 'Partial Refund')], max_length=10)),
                ('return_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_deadline', models.DateTimeField(default=core.models.default_deadline)),
                ('got_response', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dispute_responses', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_responses', to='core.dispute')),
                ('supporting_documents', models.ManyToManyField(blank=True, related_name='related_dispute_responses', to='core.supportingdocument')),
            ],
        ),
    ]
