# Generated by Django 5.0.6 on 2024-10-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_dispute_auto_resolved_dispute_got_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disputeresponse',
            name='status',
        ),
        migrations.AddField(
            model_name='disputeresponse',
            name='response',
            field=models.CharField(choices=[('no_response', 'No Response'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('counter_offer', 'Counter Offer')], default='no_response', max_length=20),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('auto_resolved', 'Auto Resolved'), ('drc_forwarded', 'DRC Forwarded')], default='open', max_length=20),
        ),
    ]
