# Generated by Django 5.0.6 on 2024-11-02 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_disputeresponse_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contract'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='milestone_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.milestone'),
        ),
    ]
