# Generated by Django 5.0.6 on 2024-11-03 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_milestone_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contract'),
        ),
        migrations.AlterField(
            model_name='counteroffer',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_offers', to='core.contract'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='milestone_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.milestone'),
        ),
    ]
