# Generated by Django 5.0.6 on 2024-11-06 07:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_disputemanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrcForwardedDisputes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('solved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dispute')),
                ('dispute_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.disputemanager')),
            ],
        ),
    ]
