# Generated by Django 5.0.6 on 2024-11-07 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_drcforwardeddisputes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrcResolvedDisputes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_type', models.CharField(choices=[('full', 'Full Refund'), ('partial', 'Partial Refund')], max_length=10)),
                ('return_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drc_forwarded', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.drcforwardeddisputes')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
