# Generated by Django 5.0.6 on 2024-11-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_drcresolveddisputes'),
    ]

    operations = [
        migrations.AddField(
            model_name='drcresolveddisputes',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drcresolveddisputes',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
