# Generated by Django 5.0.6 on 2024-11-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_drcresolveddisputes_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewer',
            name='type',
            field=models.CharField(choices=[('technical', 'Technical'), ('soft_skills', 'Soft Skills')], default='technical', max_length=20),
        ),
    ]
