# Generated by Django 5.0.6 on 2024-11-09 12:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_interviewer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finished', models.BooleanField(default=False)),
                ('personality_assessment', models.BooleanField(default=False)),
                ('depth_skill_assessment', models.BooleanField(default=False)),
                ('live_assessment', models.BooleanField(default=False)),
                ('project_assessment', models.BooleanField(default=False)),
                ('passed', models.BooleanField(default=False)),
                ('on_hold', models.BooleanField(default=False)),
                ('on_hold_duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_freelancer', models.BooleanField(default=True)),
                ('freelancer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.freelancer')),
            ],
        ),
    ]
