# Generated by Django 5.0.6 on 2024-11-09 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_fullassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullassessment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.services'),
        ),
    ]
