# Generated by Django 5.0.6 on 2024-11-10 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_fullassessment_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='position_applied_for',
        ),
        migrations.AddField(
            model_name='resume',
            name='applied_positions',
            field=models.ManyToManyField(to='core.services'),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='expertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.services'),
        ),
        migrations.AlterField(
            model_name='screeningresult',
            name='resume',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.resume'),
        ),
    ]
