# Generated by Django 5.0.6 on 2024-11-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_remove_resume_position_applied_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullassessment',
            name='service',
        ),
        migrations.AddField(
            model_name='fullassessment',
            name='applied_positions',
            field=models.ManyToManyField(to='core.services'),
        ),
    ]
