# Generated by Django 5.0.6 on 2024-11-10 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_remove_fullassessment_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningresult',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.services'),
        ),
    ]
