# Generated by Django 5.0.6 on 2024-11-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_field_services_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
