# Generated by Django 5.0.6 on 2024-11-11 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_field_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningresult',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.resume'),
        ),
    ]
