# Generated by Django 5.0.6 on 2024-11-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_screeningresult_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='interview_type',
            field=models.CharField(default=[('soft_skills', 'Soft Skills'), ('live_assessment', 'Live Assessment'), ('depth_skill_assessment', 'Depth Skill Assessment')], max_length=255),
        ),
    ]
