# Generated by Django 5.0.6 on 2024-11-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_appointment_interview_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='interview_type',
            field=models.CharField(choices=[('soft_skills', 'Soft Skills'), ('live_assessment', 'Live Assessment'), ('depth_skill_assessment', 'Depth Skill Assessment')], default='soft_skills', max_length=255),
        ),
    ]
