# Generated by Django 5.0.6 on 2024-11-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_appointment_interview_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullassessment',
            old_name='personality_assessment',
            new_name='soft_skills_assessment',
        ),
    ]
