# Generated by Django 5.0.6 on 2024-11-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_rename_personality_assessment_fullassessment_soft_skills_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='interview_type',
            field=models.CharField(choices=[('soft_skills_assessment', 'Soft Skills'), ('live_assessment', 'Live Assessment'), ('depth_skill_assessment', 'Depth Skill Assessment')], default='soft_skills_assessment', max_length=255),
        ),
    ]
