# Generated by Django 5.0.6 on 2024-11-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_appointment_interview_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullassessment',
            name='depth_skill_assessment_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('on_hold', 'On Hold')], default='not_started'),
        ),
        migrations.AddField(
            model_name='fullassessment',
            name='live_assessment_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('on_hold', 'On Hold')], default='not_started'),
        ),
        migrations.AddField(
            model_name='fullassessment',
            name='project_assessment_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('on_hold', 'On Hold')], default='not_started'),
        ),
        migrations.AddField(
            model_name='fullassessment',
            name='soft_skills_assessment_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('on_hold', 'On Hold')], default='not_started'),
        ),
    ]
