# Generated by Django 5.0.6 on 2024-11-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_fullassessment_depth_skill_assessment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullassessment',
            name='depth_skill_assessment',
        ),
        migrations.RemoveField(
            model_name='fullassessment',
            name='live_assessment',
        ),
        migrations.RemoveField(
            model_name='fullassessment',
            name='project_assessment',
        ),
        migrations.RemoveField(
            model_name='fullassessment',
            name='soft_skills_assessment',
        ),
    ]
