# Generated by Django 5.0.6 on 2024-11-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_remove_fullassessment_depth_skill_assessment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='skills_passed',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
