# Generated by Django 5.0.6 on 2024-11-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_appointment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
