# Generated by Django 5.0.6 on 2024-11-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_freelancer_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='hourly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counteroffer',
            name='hourly',
            field=models.BooleanField(default=False),
        ),
    ]
