# Generated by Django 5.0.6 on 2024-11-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_contract_hourly_counteroffer_hourly'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='duration',
            field=models.CharField(choices=[('1week', '1 Week'), ('2weeks', '2 Weeks'), ('1month', '1 Month'), ('2months', '2 Months'), ('3months', '3 Months'), ('6months', '6 Months'), ('1year', '1 Year')], default='1month', max_length=10),
        ),
    ]
