# Generated by Django 5.0.6 on 2024-11-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_contract_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='duration',
            field=models.CharField(default='1month', max_length=10),
        ),
    ]
