# Generated by Django 5.0.6 on 2024-12-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_resumechecker'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullassessment',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('on_hold', 'On Hold')], default='not_started'),
        ),
    ]
