# Generated by Django 5.0.6 on 2024-12-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_fullassessment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='counteroffer',
            name='duration',
            field=models.CharField(default='1month', max_length=10),
        ),
    ]
