# Generated by Django 5.0.6 on 2024-12-06 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_counteroffer_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullassessment',
            name='applied_positions',
        ),
        migrations.AddField(
            model_name='fullassessment',
            name='applied_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.services'),
        ),
    ]
