# Generated by Django 5.0.6 on 2024-12-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_remove_fullassessment_applied_positions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('accepted', 'accepted'), ('active', 'Active'), ('completed', 'Completed'), ('approvalPending', 'Approval Pending'), ('canceled', 'Canceled'), ('inDispute', 'InDispute')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='type',
            field=models.CharField(choices=[('technical', 'Technical'), ('soft_skills', 'Soft Skills'), ('live_interview', 'Live Interview')], default='technical', max_length=20),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'accepted'), ('inDsipute', 'InDispute'), ('approvalPending', 'Approval Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
