# Generated by Django 5.0.6 on 2024-12-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_alter_contract_status_alter_interviewer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('accepted', 'accepted'), ('active', 'Active'), ('completed', 'Completed'), ('pendingApproval', 'Pending Approval'), ('canceled', 'Canceled'), ('inDispute', 'InDispute')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'accepted'), ('inDsipute', 'InDispute'), ('pendingApproval', 'Pending Approval'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
