# Generated by Django 5.0.6 on 2024-12-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_alter_contract_status_alter_milestone_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputeresponse',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
