# Generated by Django 5.0.6 on 2024-12-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_alter_dispute_client_alter_dispute_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drcresolveddisputes',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
