# Generated by Django 5.0.6 on 2024-12-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_alter_drcresolveddisputes_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verfied',
            field=models.BooleanField(default=False),
        ),
    ]
