# Generated by Django 5.0.6 on 2024-12-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_user_email_verfied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verfied',
        ),
        migrations.AddField(
            model_name='resume',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
