# Generated by Django 5.0.6 on 2024-12-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_remove_user_email_verfied_resume_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
