# Generated by Django 5.0.6 on 2024-12-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_dispute_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('cancelled', 'Cancelled'), ('resolved', 'Resolved'), ('auto_resolved', 'Auto Resolved'), ('drc_forwarded', 'DRC Forwarded')], default='open', max_length=20),
        ),
    ]
