# Generated by Django 5.0.6 on 2025-02-04 12:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_waitlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTermination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('termination_count', models.PositiveIntegerField(default=1)),
                ('freelancer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.freelancer')),
            ],
        ),
    ]
