# Generated by Django 5.0.6 on 2025-02-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_assessmenttermination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullassessment',
            name='on_hold_duration',
        ),
        migrations.AddField(
            model_name='fullassessment',
            name='hold_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmenttermination',
            name='termination_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
