# Generated by Django 5.0.6 on 2025-02-12 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_remove_fullassessment_on_hold_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumechecker',
            name='max_resume_check_per_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='resumechecker',
            name='resume_check_per_week',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='resumechecker',
            name='working_hours_end',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='resumechecker',
            name='working_hours_start',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
