# Generated by Django 5.0.6 on 2025-02-12 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_resumechecker_max_resume_check_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passed', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resume')),
                ('resumechecker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_checks', to='core.resumechecker')),
            ],
        ),
    ]
