# Generated by Django 5.0.6 on 2025-02-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_applicationonhold'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationonhold',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
