# Generated by Django 5.0.6 on 2025-02-16 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_applicationonhold_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='applied_positions',
        ),
        migrations.AddField(
            model_name='resume',
            name='applied_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.services'),
        ),
    ]
