# Generated by Django 5.0.6 on 2025-02-16 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_remove_resume_applied_positions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumecheck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
